--
-- PostgreSQL database dump
--

\restrict RdH8612sy1kzqY8z1hrHaWejykbiPtdLipqPftCvH6TY2M1PbvwN24KE5keRbNa

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: backup; Type: TABLE; Schema: public; Owner: backup_manager_user
--

CREATE TABLE public.backup (
    id bigint NOT NULL,
    backup_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    dbname character varying(255) NOT NULL,
    path character varying(255),
    size bigint,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    owner_id bigint NOT NULL,
    CONSTRAINT backup_status_check CHECK (((status)::text = ANY ((ARRAY['CREATING'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[])))
);


ALTER TABLE public.backup OWNER TO backup_manager_user;

--
-- Name: backup_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_manager_user
--

ALTER TABLE public.backup ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.backup_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: backup_manager_user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(150) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    username character varying(255) NOT NULL,
    role character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO backup_manager_user;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: backup_manager_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: backup; Type: TABLE DATA; Schema: public; Owner: backup_manager_user
--

COPY public.backup (id, backup_name, created_at, dbname, path, size, status, updated_at, owner_id) FROM stdin;
4	backup_manager_20260928_111429	2026-09-28 11:14:47.331418	backup_manager	\N	\N	CREATING	2026-09-28 11:14:47.331538	1
5	backup_manager_20260928_125626	2026-09-28 12:56:26.751346	backup_manager	\N	\N	CREATING	2026-09-28 12:56:26.751421	1
6	backup_manager_20260929_182417	2026-09-29 18:24:17.337103	backup_manager	\N	\N	CREATING	2026-09-29 18:24:17.337144	1
7	backup_manager_20260929_202828	2026-09-29 20:28:29.098637	backup_manager	backups/backup_manager_20260929_202828.sql	4633	COMPLETED	2026-09-29 20:28:29.098722	1
8	backup_manager_20260929_202841	2026-09-29 20:28:41.684006	backup_manager	backups/backup_manager_20260929_202841.sql	4795	COMPLETED	2026-09-29 20:28:41.684072	1
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: backup_manager_user
--

COPY public.users (id, created_at, email, password, updated_at, username, role) FROM stdin;
2	2026-09-24 17:58:13.395005	reza@example.com	$2a$10$WSSrgtKPWIqra0cDF96oHe/KWcRbizKDefZyZcoPVe5ru/yhmo/8O	2026-09-24 17:58:13.39508	rerez	ROLE_USER
1	2026-09-24 17:36:12.086832	ali@example.com	$2a$10$E0y7BZS2eqiukT2qqvFxUeCUohC3aZKnoOV9qCuwOV/5etBgrgbMa	2026-09-24 17:36:12.086958	ali	ROLE_ADMIN
\.


--
-- Name: backup_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_manager_user
--

SELECT pg_catalog.setval('public.backup_id_seq', 8, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: backup_manager_user
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: backup backup_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_manager_user
--

ALTER TABLE ONLY public.backup
    ADD CONSTRAINT backup_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: backup_manager_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: backup fkct4vapypecb6ryci4395bcn5o; Type: FK CONSTRAINT; Schema: public; Owner: backup_manager_user
--

ALTER TABLE ONLY public.backup
    ADD CONSTRAINT fkct4vapypecb6ryci4395bcn5o FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: SCHEMA public; Type: ACL; Schema: -; Owner: pg_database_owner
--

GRANT ALL ON SCHEMA public TO backup_manager_user;


--
-- PostgreSQL database dump complete
--

\unrestrict RdH8612sy1kzqY8z1hrHaWejykbiPtdLipqPftCvH6TY2M1PbvwN24KE5keRbNa

