spring.application.name=backup-manager

spring.datasource.url=jdbc:postgresql://localhost:5432/backup_manager
spring.datasource.username=backup_manager_user
spring.datasource.password=1953

spring.jpa.hibernate.ddl-auto=update